version: "3.3"

services:
  app:
    ports:
      - 0.0.0.0:9292:9292
    command: rackup config.ru -o 0.0.0.0 -p 9292
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SENDER_ADDRESS: mvpip5o5aM8kfjF9zga4MC4GVqx4nMbJUY
      PRIVATE_KEY: cPZzpePWADM1DBj81zb6bBkbHzA1YxFCJfq499Pnrh2XvXZbbDZE


